//! The Tauri shell behind `pam gui`: window setup, webview context, and the IPC commands the
//! frontend may invoke. pam ships **one binary** — the GUI is not a separate app: this crate is a
//! plain library that `crates/pam` depends on, and `pam gui` calls [`run`], handing the process to
//! the Tauri event loop. Tauri's own config (`tauri.conf.json`, `capabilities/`, bundle icons, the
//! ACL-generating build script) lives in the app crate `crates/pam`, whose generated
//! `tauri::Context` [`run`] takes as its argument.
//!
//! Which frontend loads is fixed at compile time by `tauri`'s `custom-protocol` feature; this
//! crate's `embed` feature is the manual switch. Off (default, dev): `npm --prefix frontend run
//! dev` then `cargo run -p pam -- gui` — loads the Vite dev server, shows a white window if it
//! isn't running. On (production): `npm --prefix frontend run build` then `cargo build --release -p
//! pam --features gui-embed` (or `npm --prefix frontend run gui:build` for both). No feature gate
//! exists otherwise: the owner ships one binary, so CLI-only builds pay the Tauri/wry compile cost
//! too — accepted trade-off, revisit only if build times become a real problem.

pub mod bridge;
pub mod events;
pub mod logs;
pub mod service;

#[cfg(test)]
mod bridge_test;
#[cfg(test)]
mod events_test;
#[cfg(test)]
mod logs_test;
#[cfg(test)]
mod service_test;

/// Opens the pam desktop window and runs the Tauri event loop until the
/// window closes. `context` is generated by the app crate
/// (`crates/pam`), which owns `tauri.conf.json` — see the crate docs.
///
/// Must be called on the main thread (macOS requires the event loop
/// there), before any async runtime takes over the process.
///
/// # Errors
///
/// Returns an error when the platform webview runtime cannot start.
pub fn run(context: tauri::Context) -> tauri::Result<()> {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            bridge::daemon_status,
            bridge::admin_call,
            bridge::request_capability,
            bridge::daemon_stop,
            events::events_subscribe,
            logs::read_daemon_log,
            service::service_status,
            service::service_install,
            service::service_uninstall
        ])
        .run(context)
}
