[package]
name = "pam_gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cap-fs-ext.workspace = true
cap-std.workspace = true
pam_flow.workspace = true
pam_platform.workspace = true
pam_protocol.workspace = true

[lints]
workspace = true
